import { Component } from "@angular/core";
import { EndpointService } from "../../../../core/http/endpoint.service";
@Component({
  selector: "cl-publish-layout",
  templateUrl: "./publish-layout.component.html",
  styleUrl: "./publish-layout.component.scss",
})
export class PublishLayoutComponent {
   constructor(
    private EndpointService: EndpointService,
  ) {
    // this.userId = 2
  }
    ngOnInit() {
    this.getAllUser();
  }
  getAllUser() {
    this.EndpointService.getAll().subscribe((response => {
      console.log('res = ' + response);

    }))
  }
  public navList = [
    {
      id: 0,
      permissions: [],
      text: "Publish Content",
      imgUrl: "assets/icons/feature-icons/publish-icon.svg",
      icon: "far fa-pencil",
      self: true,
      link: `/publish/content`,
      exact: false,
      matIcon: false,
      expanded: false,
      canDeactivate: true,
      // children: [
      //   {
      //     id: 0,
      //     permissions: [],
      //     text: "Content Composer",
      //     icon: "far fa-pencil",
      //     self: true,
      //     // exact: true,
      //     link: `/publish/content`,
      //     matIcon: false,
      //     canDeactivate: true,
      //   },
      //   {
      //     id: 0,
      //     text: "Drafts",
      //     icon: "drafts",
      //     self: true,
      //     // exact: true,
      //     link: "/publish/draft",
      //     isChild: true,
      //     matIcon: true,
      //   },
      // ],
    },
    // {
    //   id: 1,
    //   text: "Queue",
    //   imgUrl: "assets/icons/feature-icons/queue-icon.svg",
    //   icon: "far fa-th-list",
    //   self: true,
    //   link: `/publish/queue`,
    //   exact: true,
    //   matIcon: false,
    // },
    // {
    //   id: 2,
    //   permissions: [],
    //   feature: Constants.FEATURES_ALLOWED.Suggestions,
    //   text: "Suggestion",
    //   imgUrl: "assets/icons/feature-icons/suggestion-icon.svg",
    //   icon: "far fa-bookmark",
    //   self: true,
    //   link: `/publish/suggestion`,
    //   exact: true,
    //   matIcon: false,
    // },
    // {
    //   id: 3,
    //   permissions: [],
    //   feature: Constants.FEATURES_ALLOWED.Bulk,
    //   text: "Bulk Upload",
    //   imgUrl: "assets/icons/feature-icons/bulk-upload-icon.svg",
    //   icon: "far fa-layer-group",
    //   self: true,
    //   link: "/publish/bulk-upload",
    //   exact: true,
    //   matIcon: false,
    // },
    // {
    //   id: 4,
    //   permissions: [Constants.PERMISSIONS.MANAGE_RECYCLE],
    //   feature: Constants.FEATURES_ALLOWED.Recycle,
    //   text: "Recycle",
    //   imgUrl: "assets/icons/feature-icons/recycle-icon.svg",
    //   icon: "far fa-recycle",
    //   self: true,
    //   link: `/publish/recycle`,
    //   exact: false,
    //   matIcon: false,
    //   expanded: false,
    //   children: [
    //     {
    //       id: 4,
    //       text: "Collection",
    //       icon: "far fa-recycle",
    //       self: true,
    //       link: `/publish/recycle/collection`,
    //       isChild: true,
    //     },
    //     {
    //       id: 4,
    //       text: "Campaign",
    //       icon: "far fa-recycle",
    //       self: true,
    //       link: `/publish/recycle/campaign`,
    //       isChild: true,
    //     },
    //   ],
    // },
    // {
    //   id: 5,
    //   permissions: [Constants.PERMISSIONS.MANAGE_AUTORSS],
    //   feature: Constants.FEATURES_ALLOWED.Autopost_RSS,
    //   text: "Auto RSS",
    //   imgUrl: "assets/icons/feature-icons/rss-icon.svg",
    //   icon: "far fa-rss",
    //   self: true,
    //   link: "/publish/auto-rss",
    //   exact: true,
    //   matIcon: false,
    // },
    // {
    //   id: 6,
    //   permissions: [Constants.PERMISSIONS.MANAGE_TEAM],
    //   feature: Constants.FEATURES_ALLOWED.Team,
    //   text: "Team",
    //   imgUrl: "assets/icons/feature-icons/team-icon.svg",
    //   icon: "far fa-user-friends",
    //   self: false,
    //   // link: ``,
    //   exact: true,
    //   matIcon: false,
    // },
    // {
    //   id: 7,
    //   permissions: [],
    //   text: "Post Approval",
    //   feature: Constants.FEATURES_ALLOWED.Team,
    //   imgUrl: "assets/icons/feature-icons/post-approval-icon.svg",
    //   icon: "far fa-scroll",
    //   self: true,
    //   link: "/publish/post-approval",
    //   exact: false,
    //   matIcon: false,
    // },
    // {
    //   id: 8,
    //   // permissions: [],
    //   // feature: Constants.FEATURES_ALLOWED.Settings,
    //   text: "Settings",
    //   imgUrl: "assets/icons/feature-icons/settings-icon.svg",
    //   icon: "settings",
    //   self: true,
    //   link: `/publish/settings`,
    //   exact: false,
    //   matIcon: true,
    //   expanded: false,
    //   children: [
    //     {
    //       id: 8,
    //       permissions: [],
    //       feature: Constants.FEATURES_ALLOWED.Workspace,
    //       text: "Workspace",
    //       icon: "far fa-briefcase",
    //       self: true,
    //       link: "/publish/settings/workspace",
    //       // exact: true,
    //       matIcon: false,
    //       isChild: true,
    //     },
    //     {
    //       id: 8,
    //       permissions: [Constants.PERMISSIONS.MANAGE_PROFILES],
    //       feature: Constants.FEATURES_ALLOWED.LinkShortening,
    //       text: "Link Shortening",
    //       icon: "far fa-link",
    //       self: true,
    //       link: "/publish/settings/link-shortening",
    //       // exact: true,
    //       matIcon: false,
    //       isChild: true,
    //     },
    //     {
    //       id: 8,
    //       permissions: [],
    //       text: "Manage Queue",
    //       icon: "manage-queue-svg",
    //       self: true,
    //       link: "/publish/settings/manage-queue",
    //       // exact: true,
    //       matIcon: false,
    //       isChild: true,
    //     },
    //     {
    //       id: 8,
    //       permissions: [Constants.PERMISSIONS.MANAGE_PROFILES],
    //       text: "Manage Account",
    //       icon: "manage_accounts",
    //       self: true,
    //       link: "/publish/settings/manage-social-accounts",
    //       // exact: true,
    //       matIcon: true,
    //       isChild: true,
    //     },
    //     {
    //       id: 8,
    //       permissions: [Constants.PERMISSIONS.MANAGE_PROFILES],
    //       feature: Constants.FEATURES_ALLOWED.LinkShortening,
    //       text: "UTM Tracking",
    //       icon: "utm-tracking-svg",
    //       self: true,
    //       link: "/publish/settings/tracking",
    //       // exact: true,
    //       isChild: true,
    //     },
    //     {
    //       id: 8,
    //       permissions: [],
    //       text: "Notifications",
    //       icon: "notifications",
    //       self: true,
    //       link: "/publish/settings/notification",
    //       // exact: true,
    //       matIcon: true,
    //       isChild: true,
    //     },
    //   ],
    // },
  ];
}
